import type { NextPage } from "next";
import Head from "next/head";
import getProduct from "../api/product/[id]";
import type { GetServerSideProps } from "next";
import { Product } from "@prisma/client";

interface Props {
  product: Product;
}

const Home: NextPage<Props> = ({ product }) => {
  return (
    <div>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10 flex justify-center flex-col items-center">
        <h1 className="text-2xl mb-10 uppercase">{product.name}</h1>
        <h2 className="p-4">Ingredients list</h2>
        <ul className="list-disc">
          {product.ingredients.map((ingredient, inx) => (
            <li key={inx}>{ingredient}</li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const product = await getProduct(context.query as { id: string });
  console.log(product);
  return {
    props: { product },
  };
};

export default Home;
